config/routes.rb
Rails.application.routes.draw do

  # 他ユーザーコメント
  get 'comments/new'
  get 'comments/index'
  # URL の名前を付与　つけてあげているのだ。　名前"comment/show"⇒htmlにつながる
  get 'comments/:id/show', to: 'comments#show', as: 'comment/show'
  post 'comments/create', to: 'comments#create', as: 'comment_create'
 
# 　投稿画面
  get 'posts/index', to: 'posts#index', as: 'post_index'
  get 'posts/new', to: 'posts#new', as: 'post_new'
# ↓to: 'users#show'のコントローラーを見に行く。  
  get 'posts/:id/show', to: 'posts#show', as: 'post_show'
  post 'posts/create', to: 'posts#create', as: 'post_create'
  
  # ユーザー登録画面
  get 'users/login_form', to: 'users#login_form', as: 'signin'
  post 'users/login', to: 'users#login', as: 'login'
  post 'users/logout', to: 'users#logout', as: 'user_logout'
  get 'users/index', to: 'users#index', as: "user_index"
  root 'users#new'
# ↓to: 'users#show'のコントローラーを見に行く。
  get 'users/:id/show', to: 'users#show', as: 'show'
  post 'users/create', to: 'users#create', as: 'user_create'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/add_password_to_user.rb
class AddPasswordToUser < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user, class_name: "User", foreign_key: "user_id"
    belongs_to :post, class_name: "Post", foreign_key: "post_id"

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, class_name: "User", foreign_key: "user_id"
    has_many :comments, class_name: "Coment"
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
    self.data = [
        {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
        {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
        {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
        {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
        {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
        {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
        {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
        {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
        {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
        {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
        {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
        {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
        {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
        {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
        {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
        {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}]
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image_name, ImageUploader
    has_secure_password
    has_many :posts, class_name: "Post"
    has_many :comments, class_name: "Comment"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :set_current_user

    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end

    def forbid_login_user
        if @current_user
            flash[:notice] = "すでにログインしています"
            redirect_to("/posts/index")
        end
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find_by(id: params[:id])
  end
 
  def create
    @comment = @current_user.comments.build(comment_params)
    if @comment.save  
      # 他のURLに転送（リダイレクト）するには、redirect_toメソッドを用いま
      redirect_to comment_show_path(@comment.id)
    else  
      render :new
    end
  end

  private
    def comment_params 
      params.require(:comment).permit(:comment, :user_id, :post_id)
    end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/login")
    end
    @post = Post.new
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
  end
 
  def create
    @post = @current_user.posts.build(post_params)
    if @post.save  
      # 他のURLに転送（リダイレクト）するには、redirect_toメソッドを用いま
      redirect_to post_show_path(@post.id)
    else  
      render :new
    end
  end

  private
    def post_params 
      params.require(:post).permit(:title, :traveled, :travel_day, :travel_coment, :other_coment)
    end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def ensure_correct_user
    if @current_user.id != params[:id].to_i
       flash[:notice] = "権限がありません"
       redirect_to("/posts/index")
    end
  end   


  
  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def index
    @users = User.all
  end
  
  def login_form
    
  end

  def login
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to post_index_path
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render :login_form
    end
  end

  def logout
      session[:user_id] = nil
      flash[:notice] = "ログアウトしました"
      redirect_to("/login")   
  
  end

  # データベースに保存する仕組みを書く。
  def create
    p "================="
    p params[:user]
    p "================="
    params[:user][:birthday] = "#{params[:user]["birthday(1i)"]}/#{params[:user]["birthday(2i)"]}/#{params[:user]["birthday(3i)"]}"
    @user = User.new(user_params)  
    if @user.save  
      session[:user_id] = @user.id
      redirect_to show_path(@user.id)
    else  
      render :new
    end
  end

  private
    def user_params 
      params.require(:user).permit(:user_name, :nick_name, :birthday, :user_adress, :email, :password, 
        :password_confirmation, :user_gender ,:image_name)
    end  
    # "default_user.jpg"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>ユーザー一覧</h1>
<div  class="contaner" >
    <table class="table">
        <% @comments.each do |comment| %>
        <tr>
            <td> <%= link_to comment.user_id, comment_show_path(comment) %></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/comments/new.html.erb
<h1 >コメント投稿</h1>
 <%= form_for( @comment , url: comment_create_path) do |f| %>
        コメント:<%= f.text_field :comment %><br>
 

　<%= f.submit "登録" %>
<% end %>
 

app/views/comments/show.html.erb
<h1><%= @comment.id  %>投稿内容　</h1>
<div class="card">
　<div class="card-body">   
    <h5 class="card-title"><%= @comment.comment %></h5>
    <p class="card-text"><%= @comment.user.user_name %></p>
   
</div>　

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <%= link_to "会員登録", root_path, class:"navbar-brand" %>
  <%= link_to "会員一覧", user_index_path, class:"navbar-brand" %>
  <%= link_to "投稿", post_new_path, class:"navbar-brand" %>
  <%= link_to "投稿一覧", post_index_path, class:"navbar-brand" %>
  <%= link_to "コメント投稿", "/comments/new", class:"navbar-brand" %>
  <%= link_to "ユーザーコメント一覧", "/comments/index", class:"navbar-brand" %>
  <%= link_to "ログイン画面", signin_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%# railsのリンクは　link_to から始める。　よってatag は消す %>
        <%# <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> %>
        <%# <%= link_to "投稿一覧",root_path, class: "nav-link" %> 
        <%# <%= link_to "投稿一覧",(post.new, "/posts/#{post.id}") %> 
        <%# <%= link_to "投稿一覧",users/login_form, class: "nav-link" %> 
      </li>
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/fetch-jsonp@1.1.3/build/fetch-jsonp.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
    <%= render "layouts/header" %>
      <div class = "contaner">
        <%= yield %>
      </div>
    
    <% if session[:user_id] %>
       <%# ログイン状態 %>
       <li>
          現在ログイン中のユーザーID:
          <%= session[:user_id] %>
      </li>
    <% else %>
      <%# ログアウト状態 %>
      <li>
           <%# <%= link_to "投稿一覧",users/login_form, class: "nav-link" %>  
      </li>
    <% end %>
  
  </body>
</html>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<div  class="contaner" >
    <table class="table">
        <% @posts.each do |post| %>
        <tr>
            <td> <%= link_to post.title, post_show_path(post) %></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/posts/new.html.erb
<h1>投稿</h1>
 <%= form_for( @post , url: post_create_path) do |f| %>
    タイトル:<%= f.text_field :title %><br>
    旅した場所:<%= f.text_field :traveled %><br>
    旅した日:<%= f.text_field :travel_day %><br>
    コメント:<%= f.text_field :travel_coment %><br>
    <%# 他ユーザーコメント:<%= f.text_field :other_coment %><br>             %>
    <%= f.submit "登録" %>
　<% end %>

app/views/posts/show.html.erb
<h1><%= @post.id  %>投稿内容　</h1>
<div class="card">
　<div class="card-body">   
    <h5 class="card-title"><%= @post.title %></h5>
    <p class="card-text"><%= @post.traveled %></p>
    <p class="card-text"><%= @post.travel_day %></p>
    <p class="card-text"><%= @post.travel_coment %></p>
    <p class="card-text"><%= @post.other_coment %></p>
    
</div>　


<%# 他者からのコメント %>
<%= form_for(@comment, url: comment_create_path) do |f| %>
  <%= f.text_area :comment %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.submit "コメントする" %>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<div  class="contaner" >
    <table class="table">
        <% @users.each do |user| %>
        <tr>
            <td> <%= link_to user.user_name, show_path(user) %></td>
        </tr>
        <% end %>
    </table>
</div>


user_index_path,S

app/views/users/login_form.html.erb
<% if @error_message %>
    <div class = "form-error" >
      <%= @error_message %>
    </div>
<% end %>

<%# route でログインページを　login と名前を付与した為、"/loginに変更" %>
 <%= form_tag( "/login" ) do |f| %>
    <p>メールアドレス</p>
    <input name="email" value="<%= @email %>">
    <p>パスワード</p>
    <input type　=　"password" name　=　"password" value　=　"<%= @password %>">
    <input type　=　"submit" value　=　"ログイン">
 <% end %>

app/views/users/new.html.erb
<h1>会員登録</h1>
 <%= form_for( @user , url: user_create_path) do |f| %>
    名前:<%= f.text_field :user_name %><br>
    ニックネーム:<%= f.text_field :nick_name %><br>
    生年月日:<%= f.date_select :birthday, start_year: (Time.now.year - 30), use_month_numbers: true, end_year: Time.now.year, dafault: Date.new(1989, 1, 21) %><br/>
    郵便番号: <input id="zipcode" type="text"/> <button id="search">検索</button><br/>
    住所:<%= f.text_field :user_adress, id: "address" %><br>
    メール:<%= f.text_field :email %><br>          
    性別<%= f.select :user_gender, {'男性': 1, '女性': 2}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
    パスワード:<%= f.text_field :password %><br> 
    確認用パスワード:<%= f.text_field :password_confirmation %><br> 
    <%# 住所:<%= f.select :prefecture :user_adress %><br>
    画像:<%= f.file_field :image_name, {multipart: true} %><br> 

    <select name="user[prefecture]" id="">
      <% Prefecture.all.each do |pre| %>
      <option value=<%= pre.name %> > <%= pre.name %> </option>
      <% end %>
    </select>

<%= f.submit "登録" %>
<% end %>
<script>
let search = document.getElementById('search');
search.addEventListener('click', ()=>{
    let api = 'https://zipcloud.ibsnet.co.jp/api/search?zipcode=';
    let input = document.getElementById('zipcode').value;
    let address = document.getElementById('address');
    let url = api + input;

    fetchJsonp(url, {
        timeout: 10000, //タイムアウト時間
    })
    .then((response)=>{
        console.log("ok");
        return response.json();
    })
    .then((data)=>{
        if(data.status === 400){ //エラー時
            console.log("error");
        }else if(data.results === null){
            console.log("error");
        } else {
            console.log(data.results[0]);
            address.value = data.results[0].address1 + data.results[0].address2 + data.results[0].address3;
        }
    })
    .catch((ex)=>{ //例外処理
        console.log(ex);
    });
}, false);
</script>

app/views/users/show.html.erb
<h1>ユーザーID:<%= @user.id  %>の内容　</h1>
<%# <% if @user.id == @current_user.id %> %>
  <div class="card">
　  <div class="card-body">   
      <h5 class="card-title"><%= @user.user_name %></h5>
      <p class="card-text"><%= @user.nick_name %></p>
      <p class="card-text"><%= @user.birthday %></p>
      <p class="card-text"><%= @user.user_adress %></p>
      <p class="card-text"><%= @user.email %></p>
      <% if @user.user_gender == 1%>
        <p class="card-text">男</p>
      <% else %>
        <p class="card-text">女</p>
      <% end %>
      <p class="card-text"><%= @user.password %></p>
      <p class="card-text"><%= @user.password_confirmation %></p>
      <% if @user.image_name %>
        <p class="card-text"><%= image_tag @user.image_name.url %></p>
      <% end %>
    </div>
  </div>　
  <% link_to("編集", "/users/#{@user.id}/edit") %>